### ISSUE TITLE
Class '\kartik\widgets\DateTimePicker' not found

### ISSUE THREAD

**Issue by pctin** [kartik-v/yii2-field-range#17]
I use FieldRange as the following:
        
        use kartik\field\FieldRange;

        FieldRange::widget([
            'form' => $form,
            'model' => $model,
            'label' => 'Enter time range',
            'attribute1' => 'time_start',
            'attribute2' => 'time_end',
            'type' => FieldRange::INPUT_DATETIME,
        ]);

but get the error: "_Class '\kartik\widgets\DateTimePicker' not found_"
I see in the class FieldRange, you use this namespace of DateTimePicker: 
`const INPUT_DATETIME = '\kartik\widgets\DateTimePicker';`

but really it's '\kartik\datetime\DateTimePicker';

**Comment by kartik-v** [comment]
Depends on whether you are installing `yii2-widgets` or `yii2-widget-datetimepicker`. The extensions were part of `yii2-widgets` earlier and then separated.

**Comment by pctin** [comment]
I have installed by `"kartik-v/yii2-widget-datetimepicker": "*",`.
Retry with `"kartik-v/yii2-widgets": "*",` but the namespace not change.

How to fix this? this make me a lot of confuse when install all widgets or one by one!
