### ISSUE TITLE
$separatorOptions are not used in creating the separator.

### ISSUE THREAD

**Issue by Renkas** [kartik-v/yii2-field-range#22]
$separatorOptions are not used in creating the separator. So i can't overwrite separator's class in my usecase.

HTML creation with classes is hardcoded in `getFormInput`

**Comment by kartik-v** [comment]
This is not correct ... `separatorOptions` can be used to add in your own classes... can you confirm what is the issue?

**Comment by Renkas** [comment]
It is not used if I have set `ActiveForm` instance through `$form`. In this case separator is rendered in `getFormInput` and it's hardcoded there - without using any `$separatorOptions`

**Comment by kartik-v** [comment]
I see... will add in an enhancement.

**Comment by kartik-v** [comment]
Resolved via [updates to release 1.3.2](https://github.com/kartik-v/yii2-field-range/commit/f6635ff9f41aa88b9b13ec4bd298f00e318733b8).
