### ISSUE TITLE
On hosting Class '\kartik\widgets\DateTimePicker' not found

### ISSUE THREAD

**Issue by ifredspb** [kartik-v/yii2-field-range#26]
I use:

use kartik\datetime\DateTimePicker;

echo DateTimePicker::widget([
    'name' => 'datetime_10',
    'options' => ['placeholder' => 'Select operating time ...'],
    'convertFormat' => true,
    'pluginOptions' => [
        'todayHighlight' => true
    ]
]);

locally works

when transferring to the hosting I see this:
"PHP Fatal Error – yii\base\ErrorException
Class 'kartik\datetime\DateTimePicker' not found"

**Comment by kartik-v** [comment]
Posted in the wrong repo.

You need to check your app install and try to update packages via composer.

**Comment by ifredspb** [comment]
Sorry - the contents of all directories (except logs and debugging information) are absolutely identical.

**Comment by ifredspb** [comment]
Excuse for troubling!
After I deleted everything from the folder the vendor and downloaded again - everything worked.
