### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by JorgeDeSousa** [kartik-v/yii2-field-range#27]
## Steps to reproduce the issue

1. composer require kartik-v/yii2-field-range "dev-master"

## Actual behavior

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package 2amigos/yii2-chartjs-widget (locked at 0.1.0, required as ~2.0) is satisfiable by 2amigos/yii2-chartjs-widget[0.1.0] but these conflict with your requirements or minimum-stability.
  Problem 2
    - 2amigos/yii2-chartjs-widget 2.1.2 requires bower-asset/chartjs ~2.6 -> no matching package found.
    - 2amigos/yii2-chartjs-widget 2.1.1 requires bower-asset/chartjs ~2.6 -> no matching package found.
    - 2amigos/yii2-chartjs-widget 2.1.0 requires bower-asset/chartjs ~2.6 -> no matching package found.
    - 2amigos/yii2-chartjs-widget 2.0.2 requires bower-asset/chartjs 2.1.6 -> no matching package found.
    - 2amigos/yii2-chartjs-widget 2.0.1 requires bower-asset/chartjs 2.1.6 -> no matching package found.
    - 2amigos/yii2-chartjs-widget 2.0.0 requires bower-asset/chartjs 1.0.2 -> no matching package found.
    - Installation request for 2amigos/yii2-chartjs-widget ~2.0 -> satisfiable by 2amigos/yii2-chartjs-widget[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**_Installation failed, reverting ./composer.json to its original content._**

#### Operating System

- [x] Windows

**Comment by kartik-v** [comment]
Check your composer settings and also try with the latest update.
