### ISSUE TITLE
FieldRange::INPUT_DATE Date Format not Working.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [kartik-v/yii2-field-range#9]
Hi kartikv, I'm using the new function model DateValidator::timestampAttribute, to save the date integer data type, the widget works fine just not showing the data in the format that tells, but selecting and saving done correctly.

My Config:

        // Formatter
        'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'locale' => 'es-ES',
            'dateFormat' => 'php:d-m-yy',
            'timeFormat' => 'short',
            'defaultTimeZone' => 'America/Caracas'
        ],

My Model:

        [['Turn003', 'Turn003'], 'required'],
        [['Turn003'], 'date', 'timestampAttribute' => 'Turn003'],
        [['Turn004'], 'date', 'timestampAttribute' => 'Turn004'],

My View:

        echo kartik\field\FieldRange::widget([
            'form' => $form,
            'model' => $model,
            'label' => 'Enter date range',
            'attribute1' => 'Turn003',
            'attribute2' => 'Turn004',
            'useAddons' => false,
            'type' => kartik\field\FieldRange::INPUT_DATE,
            'widgetOptions1' => [
                'convertFormat' => true,
                'pluginOptions' => [
                    'format' => 'php:d-m-yy',
                    'todayHighlight' => true
                ]
            ],
            'widgetOptions2' => [
                'convertFormat' => true,
                'pluginOptions' => [
                    'format' => 'php:d-m-yy',
                    'todayHighlight' => true
                ]
            ],
    ]);

Show Incorrect Format;

![error_datepicker_01](https://cloud.githubusercontent.com/assets/4957021/6271791/72e4f3f4-b835-11e4-913f-7203d95340e3.jpg)

Select Date Show Correct y Save Correct:

![error_datepicker_02](https://cloud.githubusercontent.com/assets/4957021/6271793/776b60fc-b835-11e4-87e7-f88143443783.jpg)

Excuse all the inconvenience, and thank you in advance for your help,

Thks,

**Comment by kartik-v** [comment]
Check [PHP date format correctly](http://php.net/manual/en/function.date.php).

PHP does not have a format `yy`... its either `y` or `Y` ... if you put `yy` then 2015 will be parsed as `1515`...

**Comment by tecnologiaterabyte** [comment]
Thanks for your reply and change php:d-m-yy for php:d-m-Y and does not work, the change in the configuration of the formatter and the widget.

**Comment by tecnologiaterabyte** [comment]
Work with \yii\jui\DatePicker::classname() no work with kartik\widgets\DatePicker::classname(),

![error_datepicker_03](https://cloud.githubusercontent.com/assets/4957021/6274111/3912bbea-b847-11e4-80a5-7834e1977f54.jpg)

**Comment by tecnologiaterabyte** [comment]
The error I think this where the widget-datepicker is not taking formatter settings to display the date, I think it should have an option for the widget shows the date according to the configuration of the formatter.

**Comment by kartik-v** [comment]
DatePicker has not been designed to use Yii Formatter settings - you need to set format within the plugin (unless of course you are using DateControl).

**Comment by tecnologiaterabyte** [comment]
Thks, Kartikv.
